name: CI/CD

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js >= 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f